# Generated by Django 3.2.9 on 2021-11-18 20:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_controler_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controler_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 11, 18, 20, 54, 38, 520828, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Controler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chamber_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.ripening_chamber_zone')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.controler_type')),
            ],
        ),
    ]
