# Generated by Django 3.2.9 on 2021-11-18 20:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_controler_controler_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='controler_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 20, 55, 13, 14513, tzinfo=utc)),
        ),
    ]
