# Generated by Django 3.2.9 on 2021-11-18 20:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20211118_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controler_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 20, 55, 37, 113576, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('units', models.TextField(blank=True, max_length=200)),
                ('chamber_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.ripening_chamber_zone')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.sensor_type')),
            ],
        ),
    ]
