# Generated by Django 3.2.9 on 2021-11-18 20:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20211118_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controler_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 20, 56, 0, 598079, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Sensor_measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 11, 18, 20, 56, 0, 598828, tzinfo=utc))),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.sensor')),
            ],
        ),
    ]
