# Generated by Django 3.2.9 on 2021-11-18 20:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20211118_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controler_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 20, 56, 11, 812408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sensor_measure',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
