# Generated by Django 3.2.9 on 2021-11-18 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20211118_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controler_record',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
