# Generated by Django 3.2.9 on 2021-11-22 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_controler_record_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='controler_record',
            name='controler',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='devices.controler'),
        ),
    ]
