# Generated by Django 3.2.9 on 2021-11-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_controler_record_controler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controler_record',
            name='status',
            field=models.CharField(choices=[('True', True), ('False', False)], default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='sensor_measure',
            name='measure',
            field=models.IntegerField(),
        ),
    ]
