# Generated by Django 3.2.9 on 2021-12-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20211122_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='controler',
            name='chart_url',
            field=models.URLField(default=None),
        ),
    ]
