# Generated by Django 3.2.9 on 2021-12-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_alter_controler_chart_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='chart_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='controler',
            name='chart_url',
            field=models.URLField(blank=True),
        ),
    ]
