# Generated by Django 3.2.9 on 2021-11-18 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.TextField()),
                ('ripening_period', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
